boosting_round_num: 100
database_settings:
  database_file_path: /data/database/sqlite/gaiaml.db
  database_name: gaiaml_db
  database_type: sqlite
  host: localhost
  password: secure_password
  port: 5432
  username: gaia_user
is_active: true
logging:
  level: INFO
  log_file_path: /logs/gaiaml.log
  rt_log_file_path: /logs/rt_log.log
project_name: GaiaML
version: 1.0.2
welcome_message: '

  Welcome to GaiaML!'
